// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: pb/db_proxy.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *UrlReq) Reset() {
	*x = UrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_db_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlReq) ProtoMessage() {}

func (x *UrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_db_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlReq.ProtoReflect.Descriptor instead.
func (*UrlReq) Descriptor() ([]byte, []int) {
	return file_pb_db_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *UrlReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UrlReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UrlResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UrlResp) Reset() {
	*x = UrlResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_db_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlResp) ProtoMessage() {}

func (x *UrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_db_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlResp.ProtoReflect.Descriptor instead.
func (*UrlResp) Descriptor() ([]byte, []int) {
	return file_pb_db_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *UrlResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckUrlExReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CheckUrlExReq) Reset() {
	*x = CheckUrlExReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_db_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUrlExReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUrlExReq) ProtoMessage() {}

func (x *CheckUrlExReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_db_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUrlExReq.ProtoReflect.Descriptor instead.
func (*CheckUrlExReq) Descriptor() ([]byte, []int) {
	return file_pb_db_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *CheckUrlExReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CheckUrlExResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CheckUrlExResp) Reset() {
	*x = CheckUrlExResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_db_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUrlExResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUrlExResp) ProtoMessage() {}

func (x *CheckUrlExResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_db_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUrlExResp.ProtoReflect.Descriptor instead.
func (*CheckUrlExResp) Descriptor() ([]byte, []int) {
	return file_pb_db_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUrlExResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetUrlReq) Reset() {
	*x = GetUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_db_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlReq) ProtoMessage() {}

func (x *GetUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_db_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlReq.ProtoReflect.Descriptor instead.
func (*GetUrlReq) Descriptor() ([]byte, []int) {
	return file_pb_db_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *GetUrlReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetUrlResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *GetUrlResp) Reset() {
	*x = GetUrlResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_db_proxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlResp) ProtoMessage() {}

func (x *GetUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_db_proxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlResp.ProtoReflect.Descriptor instead.
func (*GetUrlResp) Descriptor() ([]byte, []int) {
	return file_pb_db_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *GetUrlResp) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_pb_db_proxy_proto protoreflect.FileDescriptor

var file_pb_db_proxy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x64, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2c, 0x0a, 0x06, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x23, 0x0a, 0x07, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x45, 0x78, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x22, 0x0a,
	0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x45, 0x78, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x1d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x20, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x32, 0x8a, 0x01, 0x0a, 0x07, 0x44, 0x62, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x21,
	0x0a, 0x06, 0x41, 0x64, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x33, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x45, 0x78, 0x12,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x45, 0x78, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x72, 0x6c,
	0x45, 0x78, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c,
	0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x04, 0x5a, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_db_proxy_proto_rawDescOnce sync.Once
	file_pb_db_proxy_proto_rawDescData = file_pb_db_proxy_proto_rawDesc
)

func file_pb_db_proxy_proto_rawDescGZIP() []byte {
	file_pb_db_proxy_proto_rawDescOnce.Do(func() {
		file_pb_db_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_db_proxy_proto_rawDescData)
	})
	return file_pb_db_proxy_proto_rawDescData
}

var file_pb_db_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_db_proxy_proto_goTypes = []interface{}{
	(*UrlReq)(nil),         // 0: pb.UrlReq
	(*UrlResp)(nil),        // 1: pb.UrlResp
	(*CheckUrlExReq)(nil),  // 2: pb.CheckUrlExReq
	(*CheckUrlExResp)(nil), // 3: pb.CheckUrlExResp
	(*GetUrlReq)(nil),      // 4: pb.GetUrlReq
	(*GetUrlResp)(nil),     // 5: pb.GetUrlResp
}
var file_pb_db_proxy_proto_depIdxs = []int32{
	0, // 0: pb.DbProxy.AddUrl:input_type -> pb.UrlReq
	2, // 1: pb.DbProxy.CheckUrlEx:input_type -> pb.CheckUrlExReq
	4, // 2: pb.DbProxy.GetUrl:input_type -> pb.GetUrlReq
	1, // 3: pb.DbProxy.AddUrl:output_type -> pb.UrlResp
	3, // 4: pb.DbProxy.CheckUrlEx:output_type -> pb.CheckUrlExResp
	5, // 5: pb.DbProxy.GetUrl:output_type -> pb.GetUrlResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_db_proxy_proto_init() }
func file_pb_db_proxy_proto_init() {
	if File_pb_db_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_db_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_db_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_db_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUrlExReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_db_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUrlExResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_db_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_db_proxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_db_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_db_proxy_proto_goTypes,
		DependencyIndexes: file_pb_db_proxy_proto_depIdxs,
		MessageInfos:      file_pb_db_proxy_proto_msgTypes,
	}.Build()
	File_pb_db_proxy_proto = out.File
	file_pb_db_proxy_proto_rawDesc = nil
	file_pb_db_proxy_proto_goTypes = nil
	file_pb_db_proxy_proto_depIdxs = nil
}
